### ISSUE TITLE
Malformed Http request causing connection drop(Node)

### ISSUE THREAD

**Issue by RamyaKrishna94** [Keith3895/financeTracker#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Keith3895** [comment]
Initialize .env folder in the root directory(where node.js code is written).

example .env content:
```
PORT = 4000
salt = '<a sample salt value>'
mongodb = 'mongodb://localhost:27017/test_env'
 ```
